SELECT P.LNAME, P.FNAME
FROM PATIENT P
WHERE P.NISS IN (
    SELECT DISTINCT DP.NISSPATIENT
    FROM DOSSIERPATIENT DP
      INNER JOIN (
        SELECT DISTINCT DP2.DCI, DP2.NOMCOMMEDICAMENT
        FROM DOSSIERPATIENT DP2
      ) AS DCI ON DP.DCI = DCI.DCI
    WHERE DP.DATEVENTE < DATE_SUB(CURRENT_DATE(), INTERVAL DP.DUREETRAITEMENT DAY) AND
      NOT EXISTS (
        SELECT 1
        FROM DOSSIERPATIENT DP3
        WHERE DP3.NISSPATIENT = DP.NISSPATIENT AND
          DP3.NOMCOMMEDICAMENT = DP.NOMCOMMEDICAMENT AND
          DP3.DATEVENTE >= DATE_SUB(CURRENT_DATE(), INTERVAL DP3.DUREETRAITEMENT DAY)
      )
  )