SELECT DISTINCT M.LNAME, M.INAMI
FROM MEDECIN M, DOSSIERPATIENT DP, SPECSYSTANAT S, MEDICAMENT ME
WHERE M.INAMI = DP.INAMIMED AND
  DP.NOMCOMMEDICAMENT = ME.NOMCOM AND
  ME.SYSTANAT = S.NOMSYSTANAT AND
  M.SPECIALITY != S.NOMSPEC