SELECT DISTINCT M.LNAME, M.INAMI
FROM MEDECIN M
  JOIN DOSSIERPATIENT DP ON M.INAMI = DP.INAMIMED JOIN MEDICAMENT MED ON DP.NOMCOMMEDICAMENT = MED.NOMCOM
  JOIN SPECSYSTANAT S ON MED.SYSTANAT = S.NOMSYSTANAT LEFT JOIN MEDECIN M2 ON M.INAMI = M2.INAMI AND
  S.NOMSPEC = M2.SPECIALITY
WHERE M2.INAMI IS NULL;