SELECT PATH.NOMPATH, COUNT(*)
FROM PATHOLOGIE PATH, DIAGNOSTIC DIAG
WHERE PATH.NOMPATH = DIAG.NOMPATHOLOGIE
GROUP BY PATH.NOMPATH
HAVING COUNT(*) >= ALL (
        SELECT COUNT(*)
        FROM DIAGNOSTIC DIAG2
        WHERE DIAG2.NOMPATHOLOGIE <> PATH.NOMPATH
        GROUP BY DIAG2.NOMPATHOLOGIE
    )